In [1]:
import numpy as np
import pandas as pd

In [11]:
data = {
    'Date': pd.date_range('2023-01-01', periods = 20),
    'Product': ['A','B','C','D'] * 5,
    'Region': ['East', 'West', 'North','South','East','West','North','South','East','West',
           'North','South','East','West','North','South','East','West','North','South'],
    'Sales': np.random.randint(100,1000,20),
    'Units': np.random.randint(10,100,20),
    'Rep': ['John','Marry','Bob','Alice','John','Mary','Bob','Alice','John','Mary',
       'Bob','Alice','John','Mary','Bob','Alice','John','Marry','Bob','ALice']
}
df= pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [12]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    464     22   John  January      Q1
1  2023-01-02       B   West    343     24  Marry  January      Q1
2  2023-01-03       C  North    930     56    Bob  January      Q1
3  2023-01-04       D  South    547     30  Alice  January      Q1
4  2023-01-05       A   East    830     26   John  January      Q1
5  2023-01-06       B   West    638     51   Mary  January      Q1
6  2023-01-07       C  North    441     27    Bob  January      Q1
7  2023-01-08       D  South    532     69  Alice  January      Q1
8  2023-01-09       A   East    945     82   John  January      Q1
9  2023-01-10       B   West    825     67   Mary  January      Q1
10 2023-01-11       C  North    224     64    Bob  January      Q1
11 2023-01-12       D  South    143     36  Alice  January      Q1
12 2023-01-13       A   East    668     29   John  January      Q1
13 2023-01-14       B   West    832     59   Mary  January      Q1
14 2023-01-15       C  North    114     94    Bob  January      Q1
15 2023-01-16       D  South    318     29  Alice  January      Q1
16 2023-01-17       A   East    699     74   John  January      Q1
17 2023-01-18       B   West    902     43  Marry  January      Q1
18 2023-01-19       C  North    789     60    Bob  January      Q1
19 2023-01-20       D  South    456     41  ALice  January      Q1

In [15]:
pd.pivot_table(df,values = 'Sales',index = 'Region',columns = "Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     699.0    NaN    NaN    NaN
North      NaN    NaN  441.0    NaN
South      NaN    NaN    NaN  456.0
West       NaN  825.0    NaN    NaN

In [16]:
pivot2 = pd.pivot_table(df, values = ['Sales','Units',], index = 'Region', columns = 'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     721.2    NaN    NaN    NaN  46.6   NaN   NaN   NaN
North      NaN    NaN  499.6    NaN   NaN   NaN  60.2   NaN
South      NaN    NaN    NaN  399.2   NaN   NaN   NaN  41.0
West       NaN  708.0    NaN    NaN   NaN  48.8   NaN   NaN

In [18]:
# CROSS TABLES
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0